version: '3.5'

services:
  mysql:
    image: mysql:5.6
    container_name: ccStore_mysql
    environment:
      - "MYSQL_DATABASE=ccStore"
      - "MYSQL_USER=iProxy"
      - "MYSQL_PASSWORD=GV*DD*4AeCQy7-F"
      - "MYSQL_ROOT_PASSWORD=GV*DD*4AeCQy7-F"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  web:
    image: ccStore
    container_name: ccStore_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - mysql
      
volumes:
   mysqldata:
     name: "data_mysql"
